version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: List code directory
          command: |
            ls -la
      - run:
          name: Update npm
          command: sudo npm i npm@latest -g
      - run:
          name: 'Install packages'
          command: npm install
      - run:
          name: Run Tests
          command: npm run integration:test
      - coveralls/upload:
          path_to_lcov:
            description: >
              Local path to the lcov output file produced by your test suite. An error
              will be thrown if the file can't be found. This is the file that will be
              sent to the Coveralls API.
            type: string
            default: ./coverage/lcov.info
