version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: List code directory
          command: |
            ls -la
      - run:
          name: Update npm
          command: npm i npm@latest -g
      - run:
          name: 'Install packages'
          command: |
            npm install
      - run:
          name: Install and Make
          command: npm install && make test-coverage
      - coveralls/upload
